[package]
name = "signify"
version = "0.4.1"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

keywords = [ "cryptography", "security" ]
description = "Create cryptographic signatures for files and verify them"

readme = "README.md"
license = "MIT"

homepage = "https://github.com/badboy/signify-rs"
repository = "https://github.com/badboy/signify-rs"

include = [
  "/Cargo.toml",
  "/README*",
  "/LICENSE*",
  "/src/**/*",
  "/tests/compare.sh",
  "/tests/full-cycle.sh",
  "/tests/integration.sh",
  "/examples/**/*",
]

[dependencies]
byteorder = "1.2"
rust-crypto = "0.2.36"
base64 = "0.9.0"
docopt = "0.8"
rpassword = "2"
ring = "0.12.1"
untrusted = "0.5"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
ed25519-dalek = "0.6"
rand = "0.4"
sha2 = "0.7"
